apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: remote-tools

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - daemonset.yaml
  - cronjob-health.yaml
  - cronjob-update.yaml

configMapGenerator:
  - name: remote-tools-scripts
    files:
      - ensure-exit-node-networking.sh=scripts/ensure-exit-node-networking.sh
      - apply-ts-extra-args-local.sh=scripts/apply-ts-extra-args-local.sh
      - k8s-healthcheck.sh=scripts/k8s-healthcheck.sh
      - k8s-update.sh=scripts/k8s-update.sh
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: remote-tools
    includeSelectors: false

images:
  - name: ghcr.io/brianlechthaler/remote-tools
    newTag: latest
