apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-tools
  namespace: remote-tools
  labels:
    app.kubernetes.io/name: remote-tools
    app.kubernetes.io/part-of: remote-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remote-tools
  namespace: remote-tools
  labels:
    app.kubernetes.io/name: remote-tools
    app.kubernetes.io/part-of: remote-tools
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remote-tools
  namespace: remote-tools
  labels:
    app.kubernetes.io/name: remote-tools
    app.kubernetes.io/part-of: remote-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: remote-tools
subjects:
  - kind: ServiceAccount
    name: remote-tools
    namespace: remote-tools
